name: build project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  buildjob1:
    runs-on: ubuntu-latest
    steps:
    - name: buildstep1
      uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - name: installing the dependcies      
      run: pip install -r requirements.txt
    - name: executing the test
      run: pytest  
      continue-on-error: true
    - name: testing continous work
      run: echo Testing-Work-After-Running    

